version: "3.6"

services:
    techxuexi:
        # image: techxuexi/techxuexi-amd64
        image: xuexi
        container_name: techxuexi
        restart: unless-stopped
        volumes:
            - ./xuexi:/xuexi/user
        ports:
            - 9980:80
        shm_size: 2gb
        environment:
            - CRONTIME=5 */6 * * *
            - Pushmode=6
            - ZhuanXiang=True
            - web_login_open=False
        # # 自定义拉取版本
            - Sourcepath=https://github.com/emhui-box/TechXueXi.git
            - pullbranche=feature

        # --------------------------------
        # 运行之后打开IP:9980即可
