version: "3"

services:
    techxuexi-web:
        image: techxuexi/techxuexi-amd64
        container_name: techxuexi-web
        restart: unless-stopped
        volumes:
            - ./techxuexi/users/web:/xuexi/user
        ports:
            - 9980:80
        environment:
            - CRONTIME=5 21,0,8,14 * * *
            - Pushmode=6
            - ZhuanXiang=True
            # - Scheme=https://techxuexi.js.org/jump/techxuexi-20211023.html?
        build:
            context: .
            shm_size: "2gb"
        shm_size: "2gb"

    frpc:
        image: zctmdc/frp:Alpha
        # hostname: xuexi
        container_name: frpc
        restart: always
        # network_mode: host
        environment:
            - SUBDOMAIN_HOST=frp.zctmdc.cc
            - BIND_PORT=7001
            - TOKEN=zctmdc303x
            - ADMIN_USER=admin
            - ADMIN_PWD=admin
            - ADMIN_PORT=7500
            - VHOST_HTTP_PORT=3080
            - SK=zctmdc303X
        ports:
            - 7500:7500
        healthcheck:
            test: "/opt/healthcheck/healthcheck-frpc.sh"
            interval: 30s
            timeout: 10s
            retries: 3
        command: ["/usr/sbin/frpc", "-c", "/etc/frp/frpc.ini"]
        external_links:
            - techxuexi-web:techxuexi-web
            
# 打开docker所在 IP:7500
# 用上面的 ADMIN_PWD/ADMIN_PWD登录
# 点击configure 粘贴以下代码(请取消注释)  即可使用~

# 访问地址为 {{subdomain}}.frp.zctmdc.cc
# subdomain提交之后刷新就出来了
# 或者可以查看[http_admin_UI] 上面一行的user值

# ; ------ ;
# [http_xuexi]
# type = http
# subdomain = {{ .Envs.HOSTNAME }}
# local_ip = techxuexi-web
# local_port = 80
