version: "3.6"

services:
    techxuexi:
        # image: techxuexi/techxuexi-amd64
        image: emhui/xuexi:arm64
        container_name: techxuexi
        restart: unless-stopped
        volumes:
            - ./xuexi:/xuexi/user
        ports:
            - 9980:80
        shm_size: 2gb
        environment:
            - CRONTIME=5 */6 * * *
            - Pushmode=6
            - ZhuanXiang=True
            - web_login_open=True
            - web_login_username=test
            - web_login_password=123456789

        # --------------------------------
        # 运行之后打开IP:9980即可
